global_costmap:
  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}

  robot_base_frame: base_link
  global_frame: odom
  # global_frame: map
  update_frequency: 4
  publish_frequency: 0.5
  static_map: true

#  inflation:
  inflation_radius: 0.01


